name: Update Contributors JSON

on:
  push:
    branches:
      - main  # or "master" or any branch you use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Run contributors list generator
        run: node src/assets/js/generateContributorsList.js

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/contributors/contributors.json
          git commit -m "Auto-update contributors.json" || echo "No changes to commit"
          git push
